name: tb_vision
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.0+2
  appwrite: ^13.0.0
  http: ^1.2.2
  intl: ^0.19.0
  skeletonizer: ^1.4.2
  envied: ^0.5.4+1
  ultralytics_yolo: ^0.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/questions.json
    - assets/images/otp_illustration.png
    - assets/yolo11n-fyp.mlmodel
    - assets/best.mlmodel
    - assets/lesion.jpeg
